#!/bin/sh

sudo guix system delete-generations 1w
guix home delete-generations 1w
guix package --delete-generations=1w
guix pull --delete-generations=1w
guix gc
guix gc --clear-failures
# sudo guix gc --vacuum-database
# guix gc --optimize
