#!/bin/sh

# exit on error
set -e

# automatically killed when script finishes
elogind-inhibit --who="$0" sleep infinity &

# Update local Emacs source
cd /home/pancake/src/emacs/emacs
git stash
git rebase --no-gpg-sign

# Update local org-mode source
cd /home/pancake/src/emacs/org-mode
git stash
git rebase --no-gpg-sign

# Update local arei source
cd /home/pancake/src/emacs/emacs-arei
git stash
git rebase --no-gpg-sign

guix pull

mv -f /home/pancake/.config/guix/dnsmasq2 /home/pancake/.config/guix/dnsmasq2.bak
wget -P /home/pancake/.config/guix https://big.oisd.nl/dnsmasq2

# don't stop on error
set +e

# dev environment
rm /home/pancake/.config/guix/dev
guix shell --pure -D guix -D emacs-next-pgtk --root=/home/pancake/.config/guix/dev -- echo "done"

# build manifest
guix build --max-jobs=4 --keep-going -m /home/pancake/.config/guix/default-manifest.scm
guix build --max-jobs=4 --keep-going -m /home/pancake/.config/guix/emacs-manifest.scm

# build system
guix system build --max-jobs=4 --keep-going /home/pancake/.config/guix/config.scm

# build home
guix home build --max-jobs=4 --keep-going /home/pancake/.config/guix/home.scm

# Display news
guix pull --news
