#!/bin/sh

# exit on error
set -e

CURRENT_TIME=$(date +"%s")
file_younger_then(){
    if [ $(( CURRENT_TIME - $2 )) -lt "$(stat -c %Z "$1")" ];
    then
        true
    else
        false
    fi
}

git_commit_time(){
    git log "$1" -n 1 --format=%ct
}

rebase_local_repository(){
    (cd "$1" &&
         git rebase --no-gpg-sign --autostash)
}

rebase_local_repository /home/pancake/src/ledger
rebase_local_repository /home/pancake/src/emacs/emacs
rebase_local_repository /home/pancake/src/emacs/org-mode
rebase_local_repository /home/pancake/src/emacs/emacs-arei
rebase_local_repository /home/pancake/src/emacs/proof-general

# used in home.scm as a channel
rebase_local_repository /home/pancake/src/nonguix
(cd /home/pancake/src/nonguix &&
     git fetch origin +keyring:keyring)

GUIX_SOURCE=/home/pancake/src/guix
rebase_local_repository $GUIX_SOURCE
(cd $GUIX_SOURCE &&
     git fetch origin +keyring:keyring)
GUIX_COMMIT=$(cd $GUIX_SOURCE && git rev-parse origin/HEAD)
CURRENT_GUIX_COMMIT=$(guix describe -f recutils | grep --max-count=1 '^commit: ' | cut -c 9-)
if (cd $GUIX_SOURCE &&
        [ $(("$(git_commit_time "$CURRENT_GUIX_COMMIT")" + (60*60*24))) -lt "$(git_commit_time "$GUIX_COMMIT")" ] );
then
    # TODO: it would be nice if I could just specify "--commit=origin/HEAD"
    guix pull --max-jobs=4 --url=$GUIX_SOURCE --commit="$GUIX_COMMIT"
else
    echo "Skipping guix pull"
fi

(cd /home/pancake/.config/guix &&
     if [ -f "dnsmasq2" ] && file_younger_then dnsmasq2 $((60*60*24)); then
         echo "Re-using existing dnsmasq2"
     else
         if [ -f "dnsmasq2" ]; then
             mv -f dnsmasq2 dnsmasq2.bak
         fi
             wget https://big.oisd.nl/dnsmasq2
     fi)

guix system build --max-jobs=4 --keep-going /home/pancake/.config/guix/config.scm

# Display news
guix pull --news

# Local Variables:
# compile-command: "./update"
# End:
