#!/bin/sh

# exit on error
set -e

CURRENT_TIME=$(date +"%s")
file_younger_then(){
    if [ $(( CURRENT_TIME - $2 )) -lt "$(stat -c %Y "$1")" ];
    then
        true
    else
        false
    fi
}

git_commit_time(){
    git log "$1" -n 1 --format=%ct
}

# Update local Emacs source
(cd /home/pancake/src/emacs/emacs &&
     git stash &&
     git rebase --no-gpg-sign)

# Update local org-mode source
(cd /home/pancake/src/emacs/org-mode &&
     git stash &&
     git rebase --no-gpg-sign)

# Update local arei source
(cd /home/pancake/src/emacs/emacs-arei &&
     git stash &&
     git rebase --no-gpg-sign)

GUIX_SOURCE=/home/pancake/src/guix
GUIX_COMMIT=$( cd $GUIX_SOURCE && git rev-parse origin/HEAD )
CURRENT_GUIX_COMMIT=$(guix describe -f recutils | grep --max-count=1 '^commit: ' | cut -c 9-)
if (cd $GUIX_SOURCE &&
        [ $(("$(git_commit_time "$CURRENT_GUIX_COMMIT")" + (60*60*24))) -lt "$(git_commit_time "$GUIX_COMMIT")" ] );
then
    # TODO: it would be nice if I could just specify "--commit=origin/HEAD"
    guix pull --max-jobs=4 --url=$GUIX_SOURCE --commit="$GUIX_COMMIT"
else
    echo "Skipping guix pull"
fi

(cd /home/pancake/.config/guix &&
     if file_younger_then dnsmasq2 $((60*60*24)); then
         echo "Re-using existing dnsmasq2"
     else
         mv -f dnsmasq2 dnsmasq2.bak &&
             wget https://big.oisd.nl/dnsmasq2
     fi)

# don't stop on error
set +e

# dev environment
rm /home/pancake/.config/guix/dev
guix shell --pure -D guix -D emacs-next-pgtk --root=/home/pancake/.config/guix/dev -- echo "done"

# build manifest
guix build --max-jobs=4 --keep-going -m /home/pancake/.config/guix/default-manifest.scm
guix build --max-jobs=4 --keep-going -m /home/pancake/.config/guix/emacs-manifest.scm

# build system
guix system build --max-jobs=4 --keep-going /home/pancake/.config/guix/config.scm

# build home
guix home build --max-jobs=4 --keep-going /home/pancake/.config/guix/home.scm

# Display news
guix pull --news

# Local Variables:
# compile-command: "./update"
# End:
