#!/usr/bin/env sh
# A general audio interface for LARBS.

[ -z "$2" ] && num="2" || num="$2"

case "$1" in
	u*) pulsemixer --change-volume +"$num" ; notify volume ;;
	d*) pulsemixer --change-volume -"$num" ; notify volume ;;
	m*) pulsemixer --toggle-mute ; notify mute ;;
	truemute) pulsemixer --mute ; notify mute ;;
	play) mpc play ; notify song ;;
	n*) mpc next ; notify song ;;
	prev) mpc prev ; notify song ;;
	t*) mpc toggle ; notify songstatus ;;
	p*) mpc pause ; pauseallmpv ;;
	f*) mpc seek +"$num" ; notify songstatus ;;
	b*) mpc seek -"$num" ; notify songstatus ;;
	r*) mpc seek 0% ; notify songstatus ;;
	*) cat << EOF
lmc: cli music interface for mpd and pulse for those with divine intellect too
grand to remember the mpc/pamixer commands.

Allowed options:
  up NUM	Increase volume (2 secs default)
  down NUM	Decrease volume (2 secs default)
  mute		Toggle mute
  truemute	Mute
  next		Next track
  prev		Previous track
  toggle	Toggle pause
  truepause	Pause
  foward NUM	Seek foward in song (2 secs default)
  back NUM	Seek back in song (2 secs default)
  restart	Restart current song
  all else	Print this message

All of these commands, except for \`truemute\`, \`prev\` and \`play\` can be truncated,
i.e. \`lmc r\` for \`lmc restart\`.
EOF
esac
