#!/bin/sh

if [ -z "$1" ] || [ -z "$2" ]; then
	echo "Usage: $0 Device_Identifier Device_Name"
	exit 1
fi

if xinput --list-props "$1" | grep -q "Device Enabled.*1$"; then
	xinput disable "$1"
	echo "$2 disabled!"
else
	xinput enable "$1"
	echo "$2 enabled!"
fi
