#!/bin/sh
alias \
    mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    tsm="transmission-remote" \
    tsmd="transmission-daemon" \
    plant="java -jar /usr/local/etc/plantuml/plantuml.jar" \

    command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % "$EDITOR" % ;}

z() { zathura "$@" & }
