#!/bin/sh
#Asynchronously sync all your mailboxes. I set my mail up using Luke Smith's (LukeSmith.xyz) mutt-wizard

mail_refresh(){
	i=0;
	accounts=$(ls "$HOME/.local/share/mail");
	for account in $accounts;
		do (mbsync "$account" > /dev/null 2>&1) &
			eval pid$i="$!";
			i=$((i+1));
	done;
}

wait_for_finish(){
	j=0;
	while [ $j -lt $i ]
	do eval tail --pid=\$pid$j -f /dev/null
		j=$((j+1));
	done;
}


mail_refresh;

if [ "$1" = "-t" ] # For when I don't have notifications (like in the framebuffer)
then
	wait_for_finish;
	echo "Mail Updated";
else
	{ wait_for_finish; notify-send "Mail Updated"; } &
	neomutt;
fi

