#!/bin/sh

xinput --list-props "AlpsPS/2 ALPS DualPoint TouchPad" | grep -q "Device Enabled.*1$" && xinput disable "AlpsPS/2 ALPS DualPoint TouchPad" || xinput enable "AlpsPS/2 ALPS DualPoint TouchPad"
