#!/bin/sh
# Disable access control for the current user.
xhost +SI:localuser:"$USER"

# Make Java applications aware this is a non-reparenting window manager.
export _JAVA_AWT_WM_NONREPARENTING=1

# Set default cursor.
xsetroot -cursor_name left_ptr

# no beeping please
xset -b

# Set keyboard repeat rate.
xset r rate 200 60

xset +fp $(dirname $(readlink -f /var/guix/profiles/system/profile/share/fonts/truetype/fonts.dir))

# Automatically hide cursor
command -v unclutter && unclutter -idle 1 &

# A compositor (optional)
command -v picom && picom -b

# A policykit agent to allow processes to elevate their privileges
command -v lxqt-policykit-agent && lxqt-policykit-agent &

# Blank screen and lock after 3 minutes
xset dpms 0 0 180
xss-lock -- slock &

# This lets ssh-agent know what screen I'm using
gpg-connect-agent "UPDATESTARTUPTTY" /bye

if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
      eval $(dbus-launch --sh-syntax --exit-with-x11)
fi

# Finally start Emacs
exec emacs --fullscreen -f server-start
